import esbuild from "esbuild";
import { builtinModules } from "node:module";
import process from "process";

// node-ical uses randomUUID to give non-UID calendar components a unique key.
// Obsidian Mobile does not provide Node's `node:crypto` module, but does provide
// the Web Crypto API. Bundle the small compatibility implementation instead of
// leaving this one Node built-in external with the rest of them.
const externalBuiltins = builtinModules
	.flatMap((module) => [module, `node:${module}`])
	.filter((module) => module !== "node:crypto");

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const devBuild = (process.argv[2] === "dev-build");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	alias: {
		"node:crypto": "./src/cryptoShim.ts",
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...externalBuiltins],
	format: "cjs",
	target: "es2020",
	logLevel: prod ? "debug" : "info",
	sourcemap: prod ? false : "inline",
	minify: prod ? true : false,
	treeShaking: prod ? true : false,
	outfile: prod ? "dist/main.js" : "dist/main-debug.js",
});

if (prod || devBuild) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
